builders:
  graphql:
    import: "package:graphql_generator/graphql_generator.dart"
    builder_factories:
      - graphQLBuilder
    auto_apply: root_package
    build_to: cache
    build_extensions:
      .dart:
        - graphql_generator.g.part
    required_inputs:
      - angel_serialize.g.part
    applies_builders:
      - source_gen|combining_builder