name: angel_oauth2
author: Tobe O <thosakwe@gmail.com>
description: A class containing handlers that can be used within Angel to build a spec-compliant OAuth 2.0 server.
homepage: https://github.com/angel-dart/oauth2.git
version: 2.3.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies: 
  angel_framework: ^2.0.0-rc.0
  angel_http_exception: ^1.0.0
  crypto: ^2.0.0
dev_dependencies: 
  angel_validate: ^2.0.0-alpha
  angel_test: ^2.0.0-alpha
  logging:
  oauth2: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
  uuid: ^2.0.0
