name: angel_websocket
description: Support for using pkg:angel_client with WebSockets. Designed for Angel.
environment:
  sdk: ">=2.0.0-dev <3.0.0"
version: 2.0.3
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_websocket
dependencies:
  angel_auth: ^2.0.0-alpha
  angel_client: ^2.0.0-alpha
  angel_framework: ^2.0.0-rc.0
  angel_http_exception: ^1.0.0
  http: ">=0.11.0 <0.13.0"
  merge_map: ^1.0.0
  meta: ^1.0.0
  stream_channel: ^2.0.0
  web_socket_channel: ^1.0.0
dev_dependencies:
  angel_container: ^1.0.0-alpha
  angel_model: ^1.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  test: ^1.0.0
