name: angel_rethink
version: 1.1.0
description: RethinkDB-enabled services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0 <3.0.0"
homepage: https://github.com/angel-dart/rethink
dependencies:
  angel_framework: ^1.1.0
  json_god: ^2.0.0-beta
  rethinkdb_driver: ^2.3.1
dev_dependencies:
  angel_client: ^1.1.0
  angel_test: ^1.1.0
  logging: ^0.11.3
  test: ^0.12.0