name: jael_web
version: 0.0.0
description: Experimental virtual DOM/SPA engine built on Jael. Supports SSR.
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  build: ^1.0.0
  build_config: ^0.3.0
  code_builder: ^3.0.0
  jael: ^2.0.0
  jael_preprocessor: ^2.0.0
  source_gen: ^0.9.0
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0