name: angel_route
description: A powerful, isomorphic routing library for Dart. It is mainly used in the Angel framework, but can be used in Flutter and on the Web.
version: 3.1.0+1
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_route
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  combinator: ^1.0.0
  meta: ^1.0.0
  path: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  http: ">=0.11.3 <0.12.0"
  pedantic: ^1.0.0
  test: ^1.0.0