name: angel_mustache
description: Mustache view generator for Angel.
author: thosakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_mustache
version: 2.0.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  file: ^5.0.0
  mustache4dart: ^3.0.0-dev
  path: ^1.0.0
dev_dependencies:
  http:
  test:
