# include: package:pedantic/analysis_options.yaml
analyzer:
  errors:
    always_declare_return_types: ignore
    omit_local_variable_types: ignore
    prefer_single_quotes: ignore
    prefer_spread_collections: ignore
  strong-mode:
    implicit-casts: false
linter:
  rules:
    - avoid_slow_async_io
    - curly_braces_in_flow_control_structures
    - unnecessary_const
    - unnecessary_new