author: Tobe O <thosakwe@gmail.com>
description: Shelf interop with Angel. Use this to wrap existing server code.
homepage: https://github.com/angel-dart/shelf
name: angel_shelf
version: 2.1.0
dependencies:
  angel_framework: ^2.0.0-alpha
  path: ^1.0.0
  shelf: ^0.7.0
  stream_channel: ^1.0.0
dev_dependencies: 
  angel_test: ^2.0.0-alpha
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  shelf_static: ^0.2.8
  test: ^1.0.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
