name: angel_client
version: 2.0.2
description: Support for querying Angel servers in the browser, Flutter, and command-line.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_client
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_http_exception: ^1.0.0
  collection: ^1.0.0
  http: ^0.12.0
  json_god: ">=2.0.0-beta <3.0.0"
  meta: ^1.0.0
  path: ^1.0.0
dev_dependencies:
  angel_framework: ^2.0.0-alpha
  angel_model: ^1.0.0
  async: ^2.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0
  mock_request: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
