name: angel_orm
version: 2.1.0-beta.3
description: Runtime support for Angel's ORM. Includes base classes for queries.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  charcode: ^1.0.0
  intl: ^0.15.7
  meta: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
