name: angel_file_service
version: 2.0.1
description: Angel service that persists data to a file on disk.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/file_service
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  file: ^5.0.0
  pool: ^1.0.0
dev_dependencies:
  test: ^1.0.0