name: angel_jinja
description: Angel support for the Jinja2 templating engine, ported from Python to Dart.
version: 1.0.0-rc.0
homepage: https://github.com/angel-dart/jinja
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  angel_framework: ^2.0.0-alpha
  jinja: ^0.0.4
dev_dependencies:
  angel_test: ^2.0.0
  path: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
