name: angel_proxy
description: Angel middleware to forward requests to another server (i.e. pub serve).
version: 2.2.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/proxy
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  http: ^0.12.0
  http_parser: ^3.0.0
  path: ^1.0.0
dev_dependencies:
  angel_test: ^2.0.0-alpha
  logging:
  mock_request:
  pedantic: ^1.0.0
  test: ^1.0.0
  
