name: jael
version: 2.0.2
description:  A simple server-side HTML templating engine for Dart. Comparable to Blade or Liquid.
author: Tobe O <thosakwe@gmail.com>
homepage: https://docs.angel-dart.dev/packages/front-end/jael
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  args: ^1.0.0
  charcode: ^1.0.0
  code_buffer: ^1.0.0
  source_span: ^1.0.0
  string_scanner: ^1.0.0
  symbol_table: ^2.0.0
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
executables:
  jaelfmt: jaelfmt