name: angel_typed_service
version: 1.0.1
description: Angel services that use reflection to (de)serialize Dart objects.
homepage: https://github.com/angel-dart/typed_service
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  json_god: ^2.0.0-beta
dev_dependencies:
  angel_file_service: ^2.0.0
  file: ^5.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  test: ^1.0.0