name: angel_validate
version: 3.0.0-alpha
description: Strongly-typed form handlers and validators for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/validate
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0
  duration: ^2.0.0
  html_builder: ^1.0.0
  http_parser: ^3.0.0
  image: ^2.0.0
  matcher: ^0.12.5
dev_dependencies:
  angel_orm: ^2.1.0-beta
  angel_orm_generator: ^2.1.0-beta
  angel_serialize: ^2.0.0
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  test: ^1.0.0
