name: angel_eventsource
version: 1.0.0
description: Server-sent Events (SSE) plugin for Angel.
homepage: https://github.com/angel-dart/eventsource
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  angel_websocket: ^2.0.0-alpha
  eventsource: ^0.2.0
  stream_channel: ^1.0.0
dev_dependencies: 
  console: ^3.0.0
  logging:
  test: ^1.0.0
