name: body_parser
author: Tobe O <thosakwe@gmail.com>
version: 1.1.1
description: Parse request bodies and query strings in Dart. Supports JSON, URL-encoded, and multi-part bodies.
homepage: https://github.com/angel-dart/body_parser
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  dart2_constant: ^1.0.0
  http_parser: ">=3.1.1 <4.0.0"
  http_server: ">=0.9.6 <1.0.0"
  mime: ">=0.9.3 <1.0.0"
dev_dependencies:
  http: ">=0.11.3 <0.12.0"
  test: ">=0.12.15"