name: angel_container_generator
version: 1.0.1
author: Tobe O <thosakwe@gmail.com>
description: Codegen support for using pkg:reflectable with pkg:angel_container.
homepage: https://github.com/angel-dart/container.git
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_container: ^1.0.0-alpha
  reflectable: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  build_test:
  test: ^1.0.0