name: angel_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  angel_mongo: ^2.0.0
  angel_framework: 2.1.1
  mongo_dart: ">= 0.2.7 < 1.0.0"

dev_dependencies:
  pedantic: ^1.8.0
