name: angel_auth_oauth2
description: angel_auth strategy for OAuth2 login, i.e. Facebook, Github, etc.
version: 2.1.0
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0-dev <3.0.0"
homepage: https://github.com/angel-dart/auth_oauth2.git
dependencies:
  angel_auth: ^2.0.0
  angel_framework: ^2.0.0-alpha
  http_parser: ^3.0.0
  oauth2: ^1.0.0
dev_dependencies:
  logging: ^0.11.0
  pedantic: ^1.0.0