name: angel_orm_generator
version: 2.1.0-beta.2
description: Code generators for Angel's ORM. Generates query builder classes.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/orm
environment:
  sdk: ">=2.0.0<3.0.0"
dependencies:
  analyzer: ">=0.35.0 <2.0.0"
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
  angel_orm: ^2.1.0-beta
  angel_serialize_generator: ^2.0.0
  build: ^1.0.0
  build_config: ^0.4.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  inflection2: ^0.4.2
  meta: ^1.0.0
  path: ^1.0.0
  recase: ^2.0.0
  source_gen: ^0.9.0
dev_dependencies:
  angel_framework: ^2.0.0-alpha
  angel_migration:
    path: ../angel_migration
  #angel_test: ^1.0.0
  build_runner: ^1.0.0
  collection: ^1.0.0
  pedantic: ^1.0.0
  postgres: ^1.0.0
  test: ^1.0.0
# dependency_overrides:
#   angel_orm:
#     path: ../angel_orm
#   angel_serialize_generator:
#     path: ../../serialize/angel_serialize_generator
