name: angel_mongo
version: 2.0.3
description: MongoDB-enabled services for the Angel framework. Well-tested.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_mongo
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  json_god: ">=2.0.0-beta <3.0.0"
  merge_map: ^1.0.0
  mongo_dart: ">= 0.2.7 < 1.0.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  pedantic: ^1.0.0
  test: ^1.0.0
